<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0-windows10.0.17763.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <InterceptorsNamespaces>$(InterceptorsNamespaces);Microsoft.Extensions.Configuration.Binder.SourceGeneration</InterceptorsNamespaces>
        <UseWPF>true</UseWPF>
		<LiveSharpEnable>true</LiveSharpEnable>
		<Platforms>AnyCPU;x86;x64</Platforms>
		<Configurations>Debug;Release;Remote</Configurations>
		<BaseOutputPath></BaseOutputPath>
		<PackageOutputPath>$(OutputPath)</PackageOutputPath>
		<ApplicationIcon>symbol.ico</ApplicationIcon>
    </PropertyGroup>

	<!-- 플랫폼별 개별 출력 디렉토리 설정 -->
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Remote|x86'">
		<OutputPath>\\172.30.1.41\Debug</OutputPath>
		<DebugType>portable</DebugType>
		<DebugSymbols>true</DebugSymbols>
	</PropertyGroup>

  <ItemGroup>
    <Compile Remove="Domain\Entities_legacy\**" />
    <EmbeddedResource Remove="Domain\Entities_legacy\**" />
    <None Remove="Domain\Entities_legacy\**" />
    <Page Remove="Domain\Entities_legacy\**" />
  </ItemGroup>


    <ItemGroup>
      <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.9" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.9">
        <PrivateAssets>all</PrivateAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0-preview.6.25358.103" />
      <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.9" />
      <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.0-preview.6.25358.103" />
      <PackageReference Include="MySqlConnector" Version="2.4.0" />
      <PackageReference Include="NAudio" Version="2.2.1" />
      <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
      <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="9.0.0" />
      <PackageReference Include="QRCoder" Version="1.6.0" />
      <PackageReference Include="Serilog" Version="4.3.0" />
      <PackageReference Include="Serilog.Extensions.Hosting" Version="9.0.0" />
      <PackageReference Include="Serilog.Formatting.Compact" Version="3.0.0" />
      <PackageReference Include="Serilog.Settings.Configuration" Version="9.0.0" />
      <PackageReference Include="Serilog.Sinks.Async" Version="2.1.0" />
      <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
      <PackageReference Include="Serilog.Sinks.Debug" Version="3.0.0" />
      <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
      <PackageReference Include="Serilog.Sinks.Seq" Version="9.0.0" />
      <PackageReference Include="SharpVectors" Version="1.8.5" />
      <PackageReference Include="SkiaSharp" Version="2.88.8" />
      <PackageReference Include="SkiaSharp.Skottie" Version="2.88.8" />
      <PackageReference Include="SkiaSharp.Views.WPF" Version="2.88.8" />
      <PackageReference Include="Stateless" Version="5.18.0" />
      <PackageReference Include="System.IO.Ports" Version="10.0.0-preview.6.25358.103" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Assets\Branch_QR.png" />
      <None Remove="Assets\Flag\AED.png" />
      <None Remove="Assets\Flag\AUD.png" />
      <None Remove="Assets\Flag\CAD.png" />
      <None Remove="Assets\Flag\CHF.png" />
      <None Remove="Assets\Flag\CNY.png" />
      <None Remove="Assets\Flag\EUR.png" />
      <None Remove="Assets\Flag\GBP.png" />
      <None Remove="Assets\Flag\HKD.png" />
      <None Remove="Assets\Flag\IDR.png" />
      <None Remove="Assets\Flag\JPY.png" />
      <None Remove="Assets\Flag\KOR.png" />
      <None Remove="Assets\Flag\MYR.png" />
      <None Remove="Assets\Flag\NZD.png" />
      <None Remove="Assets\Flag\PHP.png" />
      <None Remove="Assets\Flag\RUB.png" />
      <None Remove="Assets\Flag\SGD.png" />
      <None Remove="Assets\Flag\THB.png" />
      <None Remove="Assets\Flag\TMP.png" />
      <None Remove="Assets\Flag\TWD.png" />
      <None Remove="Assets\Flag\USD.png" />
      <None Remove="Assets\Flag\VND.png" />
      <None Remove="Assets\Fonts\NotoSansCJK\NotoSansCJKkr-Bold.otf" />
      <None Remove="Assets\Fonts\NotoSansCJK\NotoSansCJKkr-Medium.otf" />
      <None Remove="Assets\Fonts\NotoSansCJK\NotoSansCJKkr-Regular.otf" />
      <None Remove="Assets\Gif\DepositGuide\Guide_Deposit1.gif" />
      <None Remove="Assets\Gif\DepositGuide\Guide_Deposit2.gif" />
      <None Remove="Assets\Gif\DepositGuide\Guide_Deposit_AUD.gif" />
      <None Remove="Assets\Gif\DepositGuide\Guide_Deposit_CAD.gif" />
      <None Remove="Assets\Gif\DepositGuide\Guide_Deposit_CNY.gif" />
      <None Remove="Assets\Gif\DepositGuide\Guide_Deposit_EUR.gif" />
      <None Remove="Assets\Gif\DepositGuide\Guide_Deposit_GBP.gif" />
      <None Remove="Assets\Gif\DepositGuide\Guide_Deposit_HKD.gif" />
      <None Remove="Assets\Gif\DepositGuide\Guide_Deposit_IDR.gif" />
      <None Remove="Assets\Gif\DepositGuide\Guide_Deposit_JPY.gif" />
      <None Remove="Assets\Gif\DepositGuide\Guide_Deposit_KRW.gif" />
      <None Remove="Assets\Gif\DepositGuide\Guide_Deposit_MYR.gif" />
      <None Remove="Assets\Gif\DepositGuide\Guide_Deposit_PHP.gif" />
      <None Remove="Assets\Gif\DepositGuide\Guide_Deposit_SGD.gif" />
      <None Remove="Assets\Gif\DepositGuide\Guide_Deposit_THB.gif" />
      <None Remove="Assets\Gif\DepositGuide\Guide_Deposit_TWD.gif" />
      <None Remove="Assets\Gif\DepositGuide\Guide_Deposit_USD.gif" />
      <None Remove="Assets\Gif\DepositGuide\Guide_Deposit_VND.gif" />
      <None Remove="Assets\Gif\IDScan_ID.gif" />
      <None Remove="Assets\Gif\IDScan_Passport.gif" />
      <None Remove="Assets\Icon\chevron_left.svg" />
      <None Remove="Assets\Icon\ico.svg" />
      <None Remove="Assets\Icon\ico_accessibility.svg" />
      <None Remove="Assets\Icon\ico_arrow-rotate.svg" />
      <None Remove="Assets\Icon\ico_arrow_rotate.png" />
      <None Remove="Assets\Icon\ico_call.svg" />
      <None Remove="Assets\Icon\ico_charge.png" />
      <None Remove="Assets\Icon\ico_charge.svg" />
      <None Remove="Assets\Icon\ico_check.png" />
      <None Remove="Assets\Icon\ico_check.svg" />
      <None Remove="Assets\Icon\ico_chevron_down.png" />
      <None Remove="Assets\Icon\ico_chevron_left.png" />
      <None Remove="Assets\Icon\ico_chevron_right.png" />
      <None Remove="Assets\Icon\ico_chevron_right.svg" />
      <None Remove="Assets\Icon\ico_chevron_up.png" />
      <None Remove="Assets\Icon\ico_enlarge.svg" />
      <None Remove="Assets\Icon\ico_home.svg" />
      <None Remove="Assets\Icon\ico_minue.png" />
      <None Remove="Assets\Icon\ico_minue.svg" />
      <None Remove="Assets\Icon\ico_plus.png" />
      <None Remove="Assets\Icon\ico_plus.svg" />
      <None Remove="Assets\Icon\ico_stop.png" />
      <None Remove="Assets\Icon\ico_stop.svg" />
      <None Remove="Assets\Icon\ico_timer.png" />
      <None Remove="Assets\Icon\ico_timer.svg" />
      <None Remove="Assets\Icon\ico_voice.svg" />
      <None Remove="Assets\Image\Bill.png" />
      <None Remove="Assets\Image\Card.png" />
      <None Remove="Assets\Image\character-complete.png" />
      <None Remove="Assets\Image\Character.png" />
      <None Remove="Assets\Image\Common_Logo.png" />
      <None Remove="Assets\Image\Denomination\AUD_100.png" />
      <None Remove="Assets\Image\Denomination\AUD_50.png" />
      <None Remove="Assets\Image\Denomination\CAD_50.png" />
      <None Remove="Assets\Image\Denomination\CNY_100.png" />
      <None Remove="Assets\Image\Denomination\EUR_10.png" />
      <None Remove="Assets\Image\Denomination\EUR_100.png" />
      <None Remove="Assets\Image\Denomination\EUR_20.png" />
      <None Remove="Assets\Image\Denomination\EUR_50.png" />
      <None Remove="Assets\Image\Denomination\GBP_20.png" />
      <None Remove="Assets\Image\Denomination\GBP_50.png" />
      <None Remove="Assets\Image\Denomination\HKD_100.png" />
      <None Remove="Assets\Image\Denomination\HKD_1000.png" />
      <None Remove="Assets\Image\Denomination\HKD_500.png" />
      <None Remove="Assets\Image\Denomination\IDR_100000.png" />
      <None Remove="Assets\Image\Denomination\JPY_1000.png" />
      <None Remove="Assets\Image\Denomination\JPY_10000.png" />
      <None Remove="Assets\Image\Denomination\JPY_5000.png" />
      <None Remove="Assets\Image\Denomination\KRW_1000.png" />
      <None Remove="Assets\Image\Denomination\KRW_10000.png" />
      <None Remove="Assets\Image\Denomination\KRW_5000.png" />
      <None Remove="Assets\Image\Denomination\KRW_50000.png" />
      <None Remove="Assets\Image\Denomination\MYR_100.png" />
      <None Remove="Assets\Image\Denomination\PHP_1000.png" />
      <None Remove="Assets\Image\Denomination\SGD_100.png" />
      <None Remove="Assets\Image\Denomination\SGD_50.png" />
      <None Remove="Assets\Image\Denomination\THB_1000.png" />
      <None Remove="Assets\Image\Denomination\TWD_1000.png" />
      <None Remove="Assets\Image\Denomination\TWD_500.png" />
      <None Remove="Assets\Image\Denomination\USD_10.png" />
      <None Remove="Assets\Image\Denomination\USD_100.png" />
      <None Remove="Assets\Image\Denomination\USD_20.png" />
      <None Remove="Assets\Image\Denomination\USD_50.png" />
      <None Remove="Assets\Image\Denomination\VND_500000.png" />
      <None Remove="Assets\Image\Error.png" />
      <None Remove="Assets\Image\Exchange.png" />
      <None Remove="Assets\Image\exchange_buy.png" />
      <None Remove="Assets\Image\exchange_sell.png" />
      <None Remove="Assets\Image\GTF_LOGO2.bmp" />
      <None Remove="Assets\Image\Identification.png" />
      <None Remove="Assets\Image\IDScan_ID.png" />
      <None Remove="Assets\Image\IDScan_Passport.png" />
      <None Remove="Assets\Image\img_bill.png" />
      <None Remove="Assets\Image\img_bills.png" />
      <None Remove="Assets\Image\img_card.png" />
      <None Remove="Assets\Image\img_exchange.png" />
      <None Remove="Assets\Image\img_refund.png" />
      <None Remove="Assets\Image\img_scan_fail.png" />
      <None Remove="Assets\Image\img_scan_ing.png" />
      <None Remove="Assets\Image\img_scan_success.png" />
      <None Remove="Assets\Image\Info.png" />
      <None Remove="Assets\Image\Info_normal.png" />
      <None Remove="Assets\Image\Info_warn.png" />
      <None Remove="Assets\Image\LOGO_CI.png" />
      <None Remove="Assets\Image\LOGO_CI_black.png" />
      <None Remove="Assets\Image\LOGO_CI_white.png" />
      <None Remove="Assets\Image\Passport.png" />
      <None Remove="Assets\Image\Refund.png" />
      <None Remove="Assets\Image\succss.png" />
      <None Remove="Assets\Image\Terms\Terms_ko-KR.png" />
      <None Remove="Assets\Image\Withdrawal.png" />
      <None Remove="Assets\Image\bx-home-smile.png" />
      <None Remove="Assets\Image\bx-up-arrow-alt.png" />
      <None Remove="Assets\Image\Frame.png" />
      <None Remove="Assets\Image\Light.png" />
      <None Remove="Assets\Sound\*.wav" />
      <None Remove="Assets\Vector.png" />
      <None Remove="Assets\Video\IDScan_ID.mp4" />
      <None Remove="Assets\Video\IDScan_Passport.mp4" />
      <None Remove="Assets\Video\Loading.mp4" />
      <None Remove="Assets\Video\MoneyBoxVideo.mp4" />
      <None Remove="Assets\Loading.gif" />
      <None Remove="Assets\Progress.gif" />
      <None Remove="Assets\Image\Branch_QRBase.png" />
      <None Remove="Assets\Fonts\NotoSans\Static\NotoSans-Bold.ttf" />
      <None Remove="Assets\Fonts\NotoSans\Static\NotoSans-Medium.ttf" />
      <None Remove="Assets\Fonts\NotoSans\Static\NotoSans-Regular.ttf" />
      <None Remove="Assets\Fonts\NotoSans\Static\NotoSans-SemiBold.ttf" />
      <None Remove="Assets\Fonts\NotoSans\Static\NotoSansJP-Bold.ttf" />
      <None Remove="Assets\Fonts\NotoSans\Static\NotoSansJP-Medium.ttf" />
      <None Remove="Assets\Fonts\NotoSans\Static\NotoSansJP-Regular.ttf" />
      <None Remove="Assets\Fonts\NotoSans\Static\NotoSansJP-SemiBold.ttf" />
      <None Remove="Assets\Fonts\NotoSans\Static\NotoSansKR-Bold.ttf" />
      <None Remove="Assets\Fonts\NotoSans\Static\NotoSansKR-Medium.ttf" />
      <None Remove="Assets\Fonts\NotoSans\Static\NotoSansKR-Regular.ttf" />
      <None Remove="Assets\Fonts\NotoSans\Static\NotoSansKR-SemiBold.ttf" />
      <None Remove="Assets\Fonts\NotoSans\Static\NotoSansSC-Bold.ttf" />
      <None Remove="Assets\Fonts\NotoSans\Static\NotoSansSC-Medium.ttf" />
      <None Remove="Assets\Fonts\NotoSans\Static\NotoSansSC-Regular.ttf" />
      <None Remove="Assets\Fonts\NotoSans\Static\NotoSansSC-SemiBold.ttf" />
      <None Remove="Assets\Fonts\NotoSans\Static\NotoSansTC-Bold.ttf" />
      <None Remove="Assets\Fonts\NotoSans\Static\NotoSansTC-Medium.ttf" />
      <None Remove="Assets\Fonts\NotoSans\Static\NotoSansTC-Regular.ttf" />
      <None Remove="Assets\Fonts\NotoSans\Static\NotoSansTC-SemiBold.ttf" />
    </ItemGroup>

    <ItemGroup>
      <Page Update="Presentation\Window\Main\Views\MainWindowView.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
    </ItemGroup>

    <ItemGroup>
      <Resource Include="Assets\Fonts\NotoSansCJK\NotoSansCJKkr-Bold.otf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Fonts\NotoSansCJK\NotoSansCJKkr-Medium.otf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Fonts\NotoSansCJK\NotoSansCJKkr-Regular.otf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Icon\chevron_left.svg">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Icon\ico.svg">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Icon\ico_accessibility.svg">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Icon\ico_arrow-rotate.svg">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Icon\ico_arrow_rotate.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Icon\ico_call.svg">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Icon\ico_charge.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Icon\ico_charge.svg">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Icon\ico_check.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Icon\ico_check.svg">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Icon\ico_chevron_down.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Icon\ico_chevron_left.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Icon\ico_chevron_right.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Icon\ico_chevron_right.svg">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Icon\ico_chevron_up.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Icon\ico_enlarge.svg">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Icon\ico_home.svg">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Icon\ico_minue.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Icon\ico_minue.svg">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Icon\ico_plus.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Icon\ico_plus.svg">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Icon\ico_stop.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Icon\ico_stop.svg">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Icon\ico_timer.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Icon\ico_timer.svg">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Icon\ico_voice.svg">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Image\Exchange.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Image\img_bill.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Image\img_bills.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Image\img_card.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Image\img_exchange.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Image\img_refund.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Image\img_scan_fail.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Image\img_scan_ing.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Image\img_scan_success.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Image\LOGO_CI_black.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Image\LOGO_CI_white.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Image\Passport.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Fonts\NotoSans\Static\NotoSans-Bold.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Fonts\NotoSans\Static\NotoSans-Medium.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Fonts\NotoSans\Static\NotoSans-Regular.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Fonts\NotoSans\Static\NotoSans-SemiBold.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Fonts\NotoSans\Static\NotoSansJP-Bold.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Fonts\NotoSans\Static\NotoSansJP-Medium.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Fonts\NotoSans\Static\NotoSansJP-Regular.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Fonts\NotoSans\Static\NotoSansJP-SemiBold.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Fonts\NotoSans\Static\NotoSansKR-Bold.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Fonts\NotoSans\Static\NotoSansKR-Medium.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Fonts\NotoSans\Static\NotoSansKR-Regular.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Fonts\NotoSans\Static\NotoSansKR-SemiBold.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Fonts\NotoSans\Static\NotoSansSC-Bold.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Fonts\NotoSans\Static\NotoSansSC-Medium.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Fonts\NotoSans\Static\NotoSansSC-Regular.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Fonts\NotoSans\Static\NotoSansSC-SemiBold.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Fonts\NotoSans\Static\NotoSansTC-Bold.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Fonts\NotoSans\Static\NotoSansTC-Medium.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Fonts\NotoSans\Static\NotoSansTC-Regular.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Fonts\NotoSans\Static\NotoSansTC-SemiBold.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Fonts\NotoSans\CompositeFont\NotoSans.CompositeFont">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Fonts\NotoSans\CompositeFont\NotoSansKR.CompositeFont">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Fonts\NotoSans\CompositeFont\NotoSansJP.CompositeFont">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Fonts\NotoSans\CompositeFont\NotoSansSC.CompositeFont">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Fonts\NotoSans\CompositeFont\NotoSansTC.CompositeFont">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Fonts\Pretendard\Variable\PretendardVariable.ttf" />
      <Resource Include="Assets\Flag\TMP.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Content Include="Assets\Gif\DepositGuide\Guide_Deposit1.gif">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Assets\Gif\DepositGuide\Guide_Deposit2.gif">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Assets\Gif\DepositGuide\Guide_Deposit_AUD.gif">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Assets\Gif\DepositGuide\Guide_Deposit_CAD.gif">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Assets\Gif\DepositGuide\Guide_Deposit_CNY.gif">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Assets\Gif\DepositGuide\Guide_Deposit_EUR.gif">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Assets\Gif\DepositGuide\Guide_Deposit_GBP.gif">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Assets\Gif\DepositGuide\Guide_Deposit_HKD.gif">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Assets\Gif\DepositGuide\Guide_Deposit_IDR.gif">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Assets\Gif\DepositGuide\Guide_Deposit_JPY.gif">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Assets\Gif\DepositGuide\Guide_Deposit_KRW.gif">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Assets\Gif\DepositGuide\Guide_Deposit_MYR.gif">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Assets\Gif\DepositGuide\Guide_Deposit_PHP.gif">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Assets\Gif\DepositGuide\Guide_Deposit_SGD.gif">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Assets\Gif\DepositGuide\Guide_Deposit_THB.gif">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Assets\Gif\DepositGuide\Guide_Deposit_TWD.gif">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Assets\Gif\DepositGuide\Guide_Deposit_USD.gif">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Assets\Gif\DepositGuide\Guide_Deposit_VND.gif">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Assets\Sound\*.wav">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Assets\Video\IDScan_ID.mp4">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Assets\Video\IDScan_Passport.mp4">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Assets\Video\Loading.mp4">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Assets\Video\MoneyBoxVideo.mp4">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <None Remove="Assets\Image\Vector.png" />
      <Resource Include="Assets\Flag\AED.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Flag\AUD.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Flag\CAD.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Flag\CHF.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Flag\CNY.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Flag\EUR.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Flag\GBP.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Flag\HKD.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Flag\IDR.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Flag\JPY.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Flag\KOR.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Flag\MYR.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Flag\NZD.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Flag\PHP.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Flag\RUB.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Flag\SGD.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Flag\THB.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Flag\TWD.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Flag\USD.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Flag\VND.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Content Include="Assets\Image\Denomination\AUD_100.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Assets\Image\Denomination\AUD_50.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Assets\Image\Denomination\CAD_50.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Assets\Image\Denomination\CNY_100.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Assets\Image\Denomination\EUR_10.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Assets\Image\Denomination\EUR_100.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Assets\Image\Denomination\EUR_20.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Assets\Image\Denomination\EUR_50.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Assets\Image\Denomination\GBP_20.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Assets\Image\Denomination\GBP_50.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Assets\Image\Denomination\HKD_100.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Assets\Image\Denomination\HKD_1000.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Assets\Image\Denomination\HKD_500.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Assets\Image\Denomination\IDR_100000.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Assets\Image\Denomination\JPY_1000.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Assets\Image\Denomination\JPY_10000.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Assets\Image\Denomination\JPY_5000.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Assets\Image\Denomination\KRW_1000.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Assets\Image\Denomination\KRW_10000.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Assets\Image\Denomination\KRW_5000.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Assets\Image\Denomination\KRW_50000.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Assets\Image\Denomination\MYR_100.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Assets\Image\Denomination\PHP_1000.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Assets\Image\Denomination\SGD_100.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Assets\Image\Denomination\SGD_50.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Assets\Image\Denomination\THB_1000.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Assets\Image\Denomination\TWD_1000.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Assets\Image\Denomination\TWD_500.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Assets\Image\Denomination\USD_10.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Assets\Image\Denomination\USD_100.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Assets\Image\Denomination\USD_20.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Assets\Image\Denomination\USD_50.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Assets\Image\Denomination\VND_500000.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="symbol.ico" />
      <Resource Include="Assets\Image\character-complete.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Image\Character.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Image\Terms\Terms_ko-KR.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <None Remove="Assets\Gif\Progress.gif" />
      <Resource Include="Assets\Gif\IDScan_ID.gif">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Gif\IDScan_Passport.gif">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Gif\Progress.gif">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Assets\Fonts\NotoSans\CompositeFont\" />
      <Folder Include="Domain\" />
      <Folder Include="Assets\Fonts\NotoSans\Variable\" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Pr22">
        <HintPath>..\DeviceKit\libs\x86\Pr22.dll</HintPath>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Properties\Settings.Designer.cs">
        <DesignTimeSharedInput>True</DesignTimeSharedInput>
        <AutoGen>True</AutoGen>
        <DependentUpon>Settings.settings</DependentUpon>
      </Compile>
    </ItemGroup>

    <ItemGroup>
      <None Update="Properties\Settings.settings">
        <Generator>SettingsSingleFileGenerator</Generator>
        <LastGenOutput>Settings.Designer.cs</LastGenOutput>
      </None>
    </ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\DeviceKit\DeviceKit.csproj" />
	</ItemGroup>

	</Project>
