<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows10.0.17763.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Lib.Harmony" Version="2.4.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.9" />
    <PackageReference Include="System.IO.Ports" Version="10.0.0-preview.6.25358.103" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\KIOSK\Infrastructure\Devices\Abstractions\**\*.cs" Link="Abstractions\%(RecursiveDir)%(Filename)%(Extension)" />
    <Compile Include="..\KIOSK\Infrastructure\Devices\Drivers\**\*.cs" Link="Drivers\%(RecursiveDir)%(Filename)%(Extension)" />
    <Compile Include="..\KIOSK\Infrastructure\Devices\Transport\**\*.cs" Link="Transport\%(RecursiveDir)%(Filename)%(Extension)" />
    <Compile Include="..\KIOSK\Infrastructure\Devices\Runtime\Factories\**\*.cs" Link="Factories\%(RecursiveDir)%(Filename)%(Extension)" />
    <Compile Include="..\KIOSK\Infrastructure\Common\Utils\MpostPatcher.cs" Link="Utils\MpostPatcher.cs" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="MPOST">
      <HintPath>..\KIOSK\libs\x86\MPOST.dll</HintPath>
    </Reference>
    <Reference Include="Pr22">
      <HintPath>..\KIOSK\libs\x86\Pr22.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
