openapi: 3.0.3
info:
  title: MoneyBox POS API
  version: 1.0.0
  description: MoneyBox_POS_ API.xlsx 기준 (cmd 그대로, 경로 그대로)
servers:
- url: https://stage-cems.moneybox.or.kr
  description: Staging
- url: https://cems.moneybox.or.kr
  description: Production
tags:
- name: 환전율
- name: 한도 조회
- name: 환전 예약 거래
- name: 환전 예약 조회
- name: 거래 조회
- name: 온라인 예약 조회
- name: 온라인 예약 거래
- name: ' 조회'
paths:
  /api/cmdV2.php/C011:
    get:
      tags:
      - 환전율
      summary: 환전율
      description: '실제 호출: /api/cmdV2.php?cmd=C011'
      parameters:
      - name: cmd
        in: query
        required: true
        schema:
          type: string
          example: C011
      - name: key
        in: query
        required: true
        schema:
          type: string
        description: 포스 설정 키
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                    description: 오류여부
                  data:
                    type: array
                    description: 통화별 환율 목록
                    items:
                      type: object
                      properties:
                        "0":
                          type: string
                          description: 통화코드(동일값 currency)
                        currency:
                          type: string
                          description: 통화코드
                        "1":
                          type: string
                          description: 기준환율(동일값 base)
                        base:
                          type: string
                          description: 기준환율
                        "2":
                          type: string
                          description: 매입기준환율(동일값 buy)
                        buy:
                          type: string
                          description: 매입기준환율
                        "3":
                          type: string
                          description: 매각기준환율(동일값 sell)
                        sell:
                          type: string
                          description: 매각기준환율
                        "4":
                          type: string
                          description: 특별매입환율(동일값 spbuy)
                        spbuy:
                          type: string
                          description: 특별매입환율
                        "5":
                          type: string
                          description: 특별매각환율(동일값 spsell)
                        spsell:
                          type: string
                          description: 특별매각환율
  /api/cmdV2.php/C020:
    get:
      tags:
      - 한도 조회
      summary: 한도 조회
      description: '실제 호출: /api/cmdV2.php?cmd=C020'
      parameters:
      - name: cmd
        in: query
        required: true
        schema:
          type: string
          example: C020
      - name: key
        in: query
        required: true
        schema:
          type: string
        description: 포스 설정 키
      - name: number
        in: query
        required: false
        schema:
          type: string
        description: 실명번호
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                    description: 오류여부
                  ecode:
                    type: string
                    description: 오류코드
                  remain:
                    type: string
                    description: 환전 가능 금액
  /api/cmdV2.php/C033:
    get:
      tags:
      - 환전 예약 거래
      summary: 환전 예약 거래
      description: '실제 호출: /api/cmdV2.php?cmd=C033'
      parameters:
      - name: cmd
        in: query
        required: true
        schema:
          type: string
          example: C033
      - name: key
        in: query
        required: true
        schema:
          type: string
        description: 포스 설정 키
      - name: KIOSK_PID
        in: query
        required: false
        schema:
          type: string
        description: 포스 식별 코드
      - name: name
        in: query
        required: false
        schema:
          type: string
        description: 고객 이름
      - name: identity
        in: query
        required: false
        schema:
          type: string
        description: '신분증 구분 코드 (예: 1=주민등록증, 2=여권 등)'
      - name: number
        in: query
        required: false
        schema:
          type: string
        description: 신분증 또는 여권 번호
      - name: nation
        in: query
        required: false
        schema:
          type: string
        description: 국가 코드
      - name: key
        in: query
        required: true
        schema:
          type: string
        description: 키오스크 고유 식별 키
      - name: dt
        in: query
        required: false
        schema:
          type: string
        description: 거래 시각 (yyyyMMddHHmm)
      - name: unique_key
        in: query
        required: false
        schema:
          type: string
        description: 거래 번호
      - name: reserved
        in: query
        required: false
        schema:
          type: string
        description: 환전 예약의 예약번호
      - name: add_krw
        in: query
        required: false
        schema:
          type: string
        description: 지불 금액(원화)
      - name: give_change
        in: query
        required: false
        schema:
          type: string
        description: 거스름돈(원화)
      - name: lists
        in: query
        required: false
        schema:
          type: string
        description: 거래 세부 내역 (매매방법#통화#환율#수량#원화|매매방법#통화#환율#수량#원화)
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                    description: 오류여부
                  message:
                    type: string
                    description: 오류코드
  /api/cmdV2.php/C050:
    get:
      tags:
      - 환전 예약 조회
      summary: 환전 예약 조회
      description: '실제 호출: /api/cmdV2.php?cmd=C050'
      parameters:
      - name: cmd
        in: query
        required: true
        schema:
          type: string
          example: C050
      - name: key
        in: query
        required: true
        schema:
          type: string
        description: 키오스크에 설정된 키
      - name: sdt
        in: query
        required: false
        schema:
          type: string
        description: null
      - name: edt
        in: query
        required: false
        schema:
          type: string
        description: null
      - name: name
        in: query
        required: false
        schema:
          type: string
        description: 이름
      - name: mobile
        in: query
        required: false
        schema:
          type: string
        description: 전화번호
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                    description: 오류여부
                  ecode:
                    type: string
                    description: 오류코드
                  RESERVE:
                    type: string
                    description: 예약 ID
                  NAME:
                    type: string
                    description: 예약자 이름
                  MOBILE:
                    type: string
                    description: 예약자 휴대폰 번호
                  BIRTH:
                    type: string
                    description: 예약자 생년월일
                  DT:
                    type: string
                    description: 예약일
                  TM:
                    type: string
                    description: 예약 시간 범위 (시작~종료)
                  REG_DTM:
                    type: string
                    description: 예약 등록 일시
                  TTYPE:
                    type: string
                    description: 거래 유형 (B=BUY, S=SELL)
                  CRC:
                    type: string
                    description: 거래 통화 코드
                  RATE:
                    type: string
                    description: 적용 환율
                  AMT:
                    type: string
                    description: 환전 금액
                  BEF:
                    type: string
                    description: 예약 금액
  /api/cmdV2.php/C060:
    get:
      tags:
      - 거래 조회
      summary: 거래 조회
      description: '실제 호출: /api/cmdV2.php?cmd=C060'
      parameters:
      - name: cmd
        in: query
        required: true
        schema:
          type: string
          example: C060
      - name: key
        in: query
        required: true
        schema:
          type: string
        description: 키오스크에 설정된 키
      - name: seq
        in: query
        required: false
        schema:
          type: string
        description: 전화번호
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                    description: 오류여부
                  ecode:
                    type: string
                    description: 오류코드
                  TTYPE:
                    type: string
                    description: 거래 유형 (B=BUY, S=SELL)
                  NAME:
                    type: string
                    description: 고객 이름
                  IDENT_NUM:
                    type: string
                    description: 고객 신분증/여권 번호
                  REG_DTM:
                    type: string
                    description: 거래 등록 일시
                  ADD_KRW:
                    type: string
                    description: 지불 금액(원화)
                  GIVE:
                    type: string
                    description: 거스름돈(원화)
                  CRC:
                    type: string
                    description: 거래 통화 코드
                  RATE:
                    type: string
                    description: 적용 환율
                  AMT:
                    type: string
                    description: 환전 금액
  /api/cmdV2.php/C070:
    get:
      tags:
      - 온라인 예약 조회
      summary: 온라인 예약 조회
      description: '실제 호출: /api/cmdV2.php?cmd=C070'
      parameters:
      - name: cmd
        in: query
        required: true
        schema:
          type: string
          example: C070
      - name: key
        in: query
        required: true
        schema:
          type: string
        description: 키오스크에 설정된 키
      - name: sdt
        in: query
        required: false
        schema:
          type: string
        description: null
      - name: edt
        in: query
        required: false
        schema:
          type: string
        description: null
      - name: name
        in: query
        required: false
        schema:
          type: string
        description: 이름
      - name: mobile
        in: query
        required: false
        schema:
          type: string
        description: 전화번호
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                    description: 오류여부
                  ecode:
                    type: string
                    description: 오류코드
                  OKEY:
                    type: string
                    description: 예약 ID
                  NAME:
                    type: string
                    description: 예약자 이름
                  MOBILE:
                    type: string
                    description: 예약자 휴대폰 번호
                  IDENT:
                    type: string
                    description: 예약자 생년월일
                  DT:
                    type: string
                    description: 예약일
                  TM:
                    type: string
                    description: 예약 시간 범위 (시작~종료)
                  REG_DTM:
                    type: string
                    description: 예약 등록 일시
                  TTYPE:
                    type: string
                    description: 거래 유형 (B=BUY, S=SELL)
                  CRC:
                    type: string
                    description: 거래 통화 코드
                  RATE:
                    type: string
                    description: 적용 환율
                  AMT:
                    type: string
                    description: 환전 금액
                  XY:
                    type: string
                    description: 신분증 확인 여부
                  MEMBER:
                    type: string
                    description: MEMBER ID
  /api/cmdV2.php/C071:
    get:
      tags:
      - 온라인 예약 거래
      summary: 온라인 예약 거래
      description: '실제 호출: /api/cmdV2.php?cmd=C071'
      parameters:
      - name: cmd
        in: query
        required: true
        schema:
          type: string
          example: C071
      - name: key
        in: query
        required: true
        schema:
          type: string
        description: 포스 설정 키
      - name: KIOSK_PID
        in: query
        required: false
        schema:
          type: string
        description: 포스 식별 코드
      - name: name
        in: query
        required: false
        schema:
          type: string
        description: 고객 이름
      - name: identity
        in: query
        required: false
        schema:
          type: string
        description: '신분증 구분 코드 (예: 1=주민등록증, 2=여권 등)'
      - name: number
        in: query
        required: false
        schema:
          type: string
        description: 신분증 또는 여권 번호
      - name: nation
        in: query
        required: false
        schema:
          type: string
        description: 국가 코드
      - name: key
        in: query
        required: true
        schema:
          type: string
        description: 키오스크 고유 식별 키
      - name: dt
        in: query
        required: false
        schema:
          type: string
        description: 거래 시각 (yyyyMMddHHmm)
      - name: okey
        in: query
        required: false
        schema:
          type: string
        description: 온라인 예약의 예약번호
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                    description: 오류여부
                  message:
                    type: string
                    description: 오류코드
  /api/cmdV2.php/C080:
    get:
      tags:
      - ' 조회'
      summary: ' 조회'
      description: '실제 호출: /api/cmdV2.php?cmd=C080'
      parameters:
      - name: cmd
        in: query
        required: true
        schema:
          type: string
          example: C080
      - name: key
        in: query
        required: true
        schema:
          type: string
        description: 키오스크에 설정된 키
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                    description: 오류여부
                  ecode:
                    type: string
                    description: 오류코드
                  CRC:
                    type: string
                    description: 통화 코드
                  AMT:
                    type: string
                    description: 해당 통화 총 금액
