[GENERAL]
BILLS=1026
SCREENSAVER_TIME=0
SCREENSAVER_INTERVAL=4000
MONITOR_NUM=0
UPDATE_URL=https://github.com/noeyhusChoi/moenybox_devicecontroller
UPDATE_DISABLE=0
UPDATE_CHANNEL=win
RECEIPT_TEST=KOR
SAVE_SCAN_IMAGE=0
NewOCR=1
ESCROW=
SENDLOG_DATETIME=2025-07-15 23:00:08
EXCHANGE_OPTION=1
APP_STATUS=1
SMS=4
MAINTENANCE_TYPE=1

[SERVER]
KIOSK_ADMIN_PW=1234
KIOSK_NAME=본점
KIOSK_TEL=051-3456-7654
;코엑스 무인환전기 1
KIOSK_KEY=C4E7I4W5C4B6L3K4T2C4
;코엑스 무인환전기 2
;KIOSK_KEY=Y7D8O7V3X8M4A1R6P3F2
KIOSK_PWD=12345678900
KIOSK_PID=11
SERVER_URL=https://cems.moneybox.or.kr/api/cmdV2.php

[DEVICE]
;COIN500V2=0
;COIN100V2=0
;HCDM10K1=0
;HCDM10K2=0
;HCDM10K3=0
;HCDM20K3=0

COIN500V2=1
COIN100V2=2
HCDM20K1=26
HCDM20K2=4
DEPOSIT=5
PRINTER=6
QR=0
CARD=9
LED1=0
LED2=0

CDU1_1=KRW:50000
CDU1_2=KRW:10000
CDU1_3=KRW:5000
CDU1_4=KRW:1000

CDU2_1=USD:100
CDU2_2=EUR:100
CDU2_3=CNY:100
CDU2_4=JPY:10000

;CDU3_1=HKD:1000
;CDU3_2=TWD:1000
;CDU3_3=PHP:1000
;CDU3_4=VND:500000

DEPOSIT_KRW=50000, 10000, 5000, 1000
DEPOSIT_USD=100, 50, 20, 10
DEPOSIT_EUR=100, 50, 20, 10
DEPOSIT_CNY=100
DEPOSIT_JPY=10000, 5000, 1000
DEPOSIT_HKD=1000, 500, 100
DEPOSIT_SGD=100, 50
DEPOSIT_AUD=100, 50
DEPOSIT_GBP=50, 20
DEPOSIT_PHP=1000, 500
DEPOSIT_IDR=100000
DEPOSIT_MYR=100
DEPOSIT_VND=500000
DEPOSIT_TWD=1000, 500
DEPOSIT_THB=1000
DEPOSIT_CAD=50
;DEPOSIT_RUB=

LIMIT_USD=10000, 1000
LIMIT_EUR=5000, 500
LIMIT_CNY=10000, 1000
LIMIT_JPY=1000000, 100000
LIMIT_HKD=100000, 10000
LIMIT_SGD=10000, 1000
LIMIT_AUD=10000, 1000
LIMIT_GBP=2000, 200
LIMIT_PHP=10000, 1000
LIMIT_IDR=10000000, 1000000
LIMIT_MYR=10000, 1000
LIMIT_VND=5000000, 500000
LIMIT_TWD=100000, 10000
LIMIT_THB=100000, 10000
;LIMIT_RUB=
LIMIT_CAD=5000, 500

DEPOSIT_CASHBOX=2025-07-16 15:49:28

[Information_KOR]
ShopName=머니박스 본사테스트기기
ShopNo=263-93-00087
ShopTel=051-742-9998
ShopAddr=서울시 용산구 한강대로 393, 동산빌딩 5층
Owner=백윤철
TailMsg=똑똑한 환전~머니박스의 해운대점을\r\n이용해 주셔서 감사합니다

[Information_ENG]
ShopName=MONEYBOX YONGSAN
ShopNo=263-93-00087
ShopTel=02-757-0000
ShopAddr=287, Haeundaehaebyeon-ro, Haeundae-gu\r\nBusan
Owner=Kim Jungyeon
TailMsg=Smart currency exchange~\r\nThank you for using MONEYBOX YONGSAN.
