<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\KIOSK.DeviceRuntime\KIOSK.DeviceRuntime.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows10.0.17763.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Platforms>x86</Platforms>
    <PlatformTarget>x86</PlatformTarget>
    <StartupObject>KIOSK.Admin.App</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <None Update="device-descriptors.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="runtime-options.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="MySqlConnector" Version="2.4.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\KIOSK\Infrastructure\Database\DatabaseConfig.cs" Link="Infrastructure\Database\DatabaseConfig.cs" />
  </ItemGroup>

</Project>
