// <auto-generated />
using System;
using Kiosk.Infrastructure.Database.Ef;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kiosk.Migrations
{
    [DbContext(typeof(KioskDbContext))]
    [Migration("20260428051734_AddOperationalReferenceTables")]
    partial class AddOperationalReferenceTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Kiosk.Infrastructure.Database.Ef.Entities.ApiConfigEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("CREATED_AT");

                    b.Property<bool>("IsValid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("VLD");

                    b.Property<string>("KioskId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("KIOSK_ID");

                    b.Property<string>("ServerKey")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("SERVER_KEY");

                    b.Property<string>("ServerName")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("SERVER_NAME");

                    b.Property<string>("ServerUrl")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("SERVER_URL");

                    b.Property<int?>("TimeoutSeconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TIMEOUT_SECONDS");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("Id");

                    b.ToTable("server", (string)null);
                });

            modelBuilder.Entity("Kiosk.Infrastructure.Database.Ef.Entities.CurrencyEntity", b =>
                {
                    b.Property<string>("KioskId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("KIOSK_ID");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("CURRENCY_CODE");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("CultureCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT")
                        .HasColumnName("CULTURE_CODE");

                    b.Property<int>("CurrencyDecimal")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CURRENCY_DECIMAL");

                    b.Property<string>("CurrencySymbol")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT")
                        .HasColumnName("CURRENCY_SYMBOL");

                    b.Property<bool>("IsValid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("VLD");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("KioskId", "CurrencyCode");

                    b.ToTable("currency", (string)null);
                });

            modelBuilder.Entity("Kiosk.Infrastructure.Database.Ef.Entities.DepositCurrencyEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("AttributeCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("ATTRIBUTE_CODE");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("CURRENCY_CODE");

                    b.Property<decimal>("Denomination")
                        .HasColumnType("TEXT")
                        .HasColumnName("VALUE");

                    b.Property<bool>("IsValid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("VLD");

                    b.Property<string>("KioskId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("KIOSK_ID");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("Id");

                    b.HasIndex("KioskId", "CurrencyCode", "Denomination", "AttributeCode")
                        .IsUnique()
                        .HasDatabaseName("UQ_DENOM_ATTR");

                    b.ToTable("deposit_denom_attribute", (string)null);
                });

            modelBuilder.Entity("Kiosk.Infrastructure.Database.Ef.Entities.DepositDenominationEntity", b =>
                {
                    b.Property<string>("KioskId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("KIOSK_ID");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("CURRENCY_CODE");

                    b.Property<decimal>("Denomination")
                        .HasColumnType("TEXT")
                        .HasColumnName("VALUE");

                    b.Property<bool>("IsValid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("VLD");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("UPDATED_AT");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("UPDATED_BY");

                    b.HasKey("KioskId", "CurrencyCode", "Denomination");

                    b.ToTable("deposit_denom", (string)null);
                });

            modelBuilder.Entity("Kiosk.Infrastructure.Database.Ef.Entities.DeviceCatalogEntity", b =>
                {
                    b.Property<long>("CatalogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("catalog_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("device_type");

                    b.Property<string>("DriverType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("driver_type");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("model");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("vendor");

                    b.HasKey("CatalogId");

                    b.HasIndex("Vendor", "Model", "DriverType")
                        .IsUnique()
                        .HasDatabaseName("uq_catalog_vendor_model_driver");

                    b.ToTable("device_catalog", (string)null);
                });

            modelBuilder.Entity("Kiosk.Infrastructure.Database.Ef.Entities.DeviceCommEntity", b =>
                {
                    b.Property<string>("DeviceId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("device_id");

                    b.Property<string>("CommParams")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("comm_params");

                    b.Property<string>("CommPort")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("comm_port");

                    b.Property<string>("CommType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("comm_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("PollingMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("polling_ms");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("DeviceId");

                    b.ToTable("device_comm", (string)null);
                });

            modelBuilder.Entity("Kiosk.Infrastructure.Database.Ef.Entities.DeviceCommandLogEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CommandName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("command_name");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("device_name");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("error_code");

                    b.Property<DateTime>("FinishedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("finished_at");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("origin");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER")
                        .HasColumnName("success");

                    b.HasKey("Id");

                    b.ToTable("device_command_log", (string)null);
                });

            modelBuilder.Entity("Kiosk.Infrastructure.Database.Ef.Entities.DeviceInstanceEntity", b =>
                {
                    b.Property<string>("DeviceId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("device_id");

                    b.Property<long>("CatalogId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("catalog_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("device_name");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_enabled");

                    b.Property<string>("KioskId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("kiosk_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("DeviceId");

                    b.HasIndex("CatalogId");

                    b.HasIndex("KioskId", "DeviceId", "DeviceName")
                        .IsUnique()
                        .HasDatabaseName("uq_instance_kiosk_name");

                    b.ToTable("device_instance", (string)null);
                });

            modelBuilder.Entity("Kiosk.Infrastructure.Database.Ef.Entities.DeviceStatusLogEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("device_name");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("device_type");

                    b.Property<string>("KioskId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("kiosk_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("message");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("severity");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.ToTable("device_status_log", (string)null);
                });

            modelBuilder.Entity("Kiosk.Infrastructure.Database.Ef.Entities.KioskInfoEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("KIOSK_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("CREATED_AT");

                    b.Property<bool>("IsValid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("VLD");

                    b.Property<string>("Pid")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("KIOSK_PID");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("Id");

                    b.ToTable("kiosk", (string)null);
                });

            modelBuilder.Entity("Kiosk.Infrastructure.Database.Ef.Entities.KioskUpdateHistoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("KioskId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("KIOSK_ID");

                    b.Property<DateTime>("UpdateDateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("UPDATE_DATETIME");

                    b.Property<int>("UpdateNo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("UPDATE_NO");

                    b.Property<string>("UpdateSource")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("UPDATE_SOURCE");

                    b.HasKey("Id");

                    b.HasIndex("KioskId")
                        .HasDatabaseName("IX_kiosk_update_history_kiosk_id");

                    b.ToTable("kiosk_update_history", (string)null);
                });

            modelBuilder.Entity("Kiosk.Infrastructure.Database.Ef.Entities.LocaleInfoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT")
                        .HasColumnName("COUNTRY_CODE");

                    b.Property<string>("CountryNameEn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("COUNTRY_NAME_EN");

                    b.Property<string>("CountryNameKo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("COUNTRY_NAME_KO");

                    b.Property<string>("CultureCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("CULTURE_CODE");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT")
                        .HasColumnName("LANGUAGE_CODE");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("LANGUAGE_NAME");

                    b.Property<string>("LanguageNameEn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("LANGUAGE_NAME_EN");

                    b.Property<string>("LanguageNameKo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("LANGUAGE_NAME_KO");

                    b.HasKey("Id");

                    b.HasIndex("CultureCode")
                        .IsUnique()
                        .HasDatabaseName("UQ_LOCALE_CODE");

                    b.HasIndex("LanguageNameKo", "LanguageNameEn", "CountryNameKo", "CountryNameEn")
                        .IsUnique()
                        .HasDatabaseName("UQ_LOCALE_NAMES");

                    b.ToTable("locale_info", (string)null);
                });

            modelBuilder.Entity("Kiosk.Infrastructure.Database.Ef.Entities.ReceiptEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("INFO_KEY");

                    b.Property<string>("KioskId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("KIOSK_ID");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("INFO_LOCALE");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("UPDATED_AT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("INFO_VALUE");

                    b.HasKey("Id");

                    b.HasIndex("KioskId")
                        .HasDatabaseName("KIOSK_ID");

                    b.ToTable("kiosk_shop", (string)null);
                });

            modelBuilder.Entity("Kiosk.Infrastructure.Database.Ef.Entities.TransactionOutboxEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("CREATED_AT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("KioskId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("KIOSK_ID");

                    b.Property<DateTime?>("LastTriedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("LAST_TRIED_AT");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("MESSAGE_TYPE");

                    b.Property<DateTime>("NextRetryAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("NEXT_RETRY_AT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("PAYLOAD_JSON");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("RETRY_COUNT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("PENDING")
                        .HasColumnName("STATUS");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("TRANSACTION_ID");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId")
                        .HasDatabaseName("IX_transaction_outbox_transaction_id");

                    b.ToTable("transaction_outbox", (string)null);
                });

            modelBuilder.Entity("Kiosk.Infrastructure.Database.Ef.Entities.WithdrawalCassetteEntity", b =>
                {
                    b.Property<string>("KioskId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("KIOSK_ID");

                    b.Property<string>("DeviceID")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("DEVICE_ID");

                    b.Property<int>("Slot")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SLOT");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CAPACITY");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CURRENT_COUNT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("CURRENCY_CODE");

                    b.Property<decimal>("Denomination")
                        .HasColumnType("TEXT")
                        .HasColumnName("DENOMINATION");

                    b.Property<bool>("IsValid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("VLD");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("KioskId", "DeviceID", "Slot");

                    b.ToTable("cassette", (string)null);
                });

            modelBuilder.Entity("Kiosk.Infrastructure.Database.Ef.Entities.DeviceCommEntity", b =>
                {
                    b.HasOne("Kiosk.Infrastructure.Database.Ef.Entities.DeviceInstanceEntity", "Device")
                        .WithOne("Comm")
                        .HasForeignKey("Kiosk.Infrastructure.Database.Ef.Entities.DeviceCommEntity", "DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("device_comm_ibfk_1");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Kiosk.Infrastructure.Database.Ef.Entities.DeviceInstanceEntity", b =>
                {
                    b.HasOne("Kiosk.Infrastructure.Database.Ef.Entities.DeviceCatalogEntity", "Catalog")
                        .WithMany("Instances")
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("device_instance_ibfk_1");

                    b.Navigation("Catalog");
                });

            modelBuilder.Entity("Kiosk.Infrastructure.Database.Ef.Entities.DeviceCatalogEntity", b =>
                {
                    b.Navigation("Instances");
                });

            modelBuilder.Entity("Kiosk.Infrastructure.Database.Ef.Entities.DeviceInstanceEntity", b =>
                {
                    b.Navigation("Comm");
                });
#pragma warning restore 612, 618
        }
    }
}
