// <auto-generated />
using System;
using KIOSK.Infrastructure.Database.Ef;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KIOSK.Migrations
{
    [DbContext(typeof(KioskDbContext))]
    [Migration("20260113024626_AddDeviceCatalogs")]
    partial class AddDeviceCatalogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("KIOSK.Infrastructure.Database.Ef.Entities.DeviceCatalogEntity", b =>
                {
                    b.Property<long>("CatalogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("catalog_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("CatalogId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("device_type");

                    b.Property<string>("DriverType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("driver_type");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("model");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("vendor");

                    b.HasKey("CatalogId");

                    b.HasIndex("Vendor", "Model", "DriverType")
                        .IsUnique()
                        .HasDatabaseName("uq_catalog_vendor_model_driver");

                    b.ToTable("device_catalog", (string)null);
                });

            modelBuilder.Entity("KIOSK.Infrastructure.Database.Ef.Entities.DeviceCommEntity", b =>
                {
                    b.Property<string>("DeviceId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("device_id");

                    b.Property<string>("CommParams")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("comm_params");

                    b.Property<string>("CommPort")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("comm_port");

                    b.Property<string>("CommType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("comm_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("PollingMs")
                        .HasColumnType("int")
                        .HasColumnName("polling_ms");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("DeviceId");

                    b.ToTable("device_comm", (string)null);
                });

            modelBuilder.Entity("KIOSK.Infrastructure.Database.Ef.Entities.DeviceCommandLogEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CommandName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("command_name");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("device_name");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("error_code");

                    b.Property<DateTime>("FinishedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("finished_at");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("origin");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("started_at");

                    b.Property<bool>("Success")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("success");

                    b.HasKey("Id");

                    b.ToTable("device_command_log", (string)null);
                });

            modelBuilder.Entity("KIOSK.Infrastructure.Database.Ef.Entities.DeviceInstanceEntity", b =>
                {
                    b.Property<string>("DeviceId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("device_id");

                    b.Property<long>("CatalogId")
                        .HasColumnType("bigint")
                        .HasColumnName("catalog_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("device_name");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_enabled");

                    b.Property<string>("KioskId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("kiosk_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("DeviceId");

                    b.HasIndex("CatalogId");

                    b.HasIndex("KioskId", "DeviceId", "DeviceName")
                        .IsUnique()
                        .HasDatabaseName("uq_instance_kiosk_name");

                    b.ToTable("device_instance", (string)null);
                });

            modelBuilder.Entity("KIOSK.Infrastructure.Database.Ef.Entities.DeviceStatusLogEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("device_name");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("device_type");

                    b.Property<string>("KioskId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("kiosk_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("message");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("severity");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.ToTable("device_status_log", (string)null);
                });

            modelBuilder.Entity("KIOSK.Infrastructure.Database.Ef.Entities.DeviceCommEntity", b =>
                {
                    b.HasOne("KIOSK.Infrastructure.Database.Ef.Entities.DeviceInstanceEntity", "Device")
                        .WithOne("Comm")
                        .HasForeignKey("KIOSK.Infrastructure.Database.Ef.Entities.DeviceCommEntity", "DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("device_comm_ibfk_1");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("KIOSK.Infrastructure.Database.Ef.Entities.DeviceInstanceEntity", b =>
                {
                    b.HasOne("KIOSK.Infrastructure.Database.Ef.Entities.DeviceCatalogEntity", "Catalog")
                        .WithMany("Instances")
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("device_instance_ibfk_1");

                    b.Navigation("Catalog");
                });

            modelBuilder.Entity("KIOSK.Infrastructure.Database.Ef.Entities.DeviceCatalogEntity", b =>
                {
                    b.Navigation("Instances");
                });

            modelBuilder.Entity("KIOSK.Infrastructure.Database.Ef.Entities.DeviceInstanceEntity", b =>
                {
                    b.Navigation("Comm");
                });
#pragma warning restore 612, 618
        }
    }
}
